# Generated by Django 5.1.4 on 2025-01-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('prodapp', models.TextField()),
                ('category', models.CharField(choices=[('D', 'Dresses'), ('J', 'Jeans/Denims'), ('B', 'Beauty'), ('P', 'Party Dress'), ('E', 'Ethnic Dress')], max_length=2)),
                ('product_image', models.ImageField(upload_to='products_new')),
            ],
        ),
    ]
