# Generated by Django 5.1.4 on 2025-01-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zicode',
            new_name='zipcode',
        ),
    ]
