# Generated by Django 5.2.4 on 2025-07-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
