# Generated by Django 5.2.3 on 2025-07-09 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pricealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('D', 'Dresses'), ('J', 'Jeans/Denims'), ('B', 'Beauty'), ('P', 'Party Dress'), ('E', 'Ethnic Dress'), ('F', 'Food')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together={('user', 'product')},
        ),
    ]
